config/routes.rb
Saudi::Application.routes.draw do
  resources :policies

  resources :faqs

  resources :students

  get "welcome/index"

  get "welcome/landing"

  root :to => 'welcome#index'

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  attr_accessible :name
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :mobile_device?
  before_filter :prepare_for_mobile
  
  
  private
  def mobile_device?
    request.user_agent =~ /Mobile|webOS|Android/
  end
  
  def prepare_for_mobile
     request.format = :mobile if mobile_device? 
  end
  
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to faqs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @policies }
    end
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
    @policy = Policy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @policy }
    end
  end

  # GET /policies/new
  # GET /policies/new.json
  def new
    @policy = Policy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @policy }
    end
  end

  # GET /policies/1/edit
  def edit
    @policy = Policy.find(params[:id])
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(params[:policy])

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render json: @policy, status: :created, location: @policy }
      else
        format.html { render action: "new" }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /policies/1
  # PUT /policies/1.json
  def update
    @policy = Policy.find(params[:id])

    respond_to do |format|
      if @policy.update_attributes(params[:policy])
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy = Policy.find(params[:id])
    @policy.destroy

    respond_to do |format|
      format.html { redirect_to policies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render 'form' %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<h1>Listing faqs</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @faqs.each do |faq| %>
  <tr>
    <td><%= faq.question %></td>
    <td><%= faq.answer %></td>
    <td><%= link_to 'Show', faq %></td>
    <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
    <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Faq', new_faq_path %>

app/views/faqs/index.mobile.erb
<div data-role="header">
  <h1>FAQs</h1>
  <a href="javascript:history.back()" class = "ui-btn-left" data-role="button">Back</a>
</div>
 
<div data-role="content">
  <ul data-role="listview">
  
  <% @faqs.each do |faq| %>

      <li>
      
        <a href="/faqs/<%= faq.id %>" rel="external"><h3><%= faq.question %></h3></a>
        
      </li>
    
    <% end %>
  </ul>
</div>

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @faq.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @faq.answer %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/show.mobile.erb
<div data-role="header">
  <h1>FAQs - Answers</h1>
  <a href="javascript:history.back()" class = "ui-btn-left" data-role="button">Back</a>
</div>
 
<div data-role="content">

        <p id="notice"><%= notice %></p>
        
        <p>
          <strong><%= @faq.question %></strong>
        </p>
        
        <p>
          <%= @faq.answer %>
        </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saudi</title>

   <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
     <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
    		
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  

</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saudi Helper App</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
    
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
  <%= javascript_include_tag "application" %>
  <script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  
</head>

<body>
  

     
     
  <div data-role="page" class="page-class" data-add-back-btn="true">
  
          
    <%= yield %>
 
 
  </div>

</body> 

</html>

app/views/policies/_form.html.erb
<%= form_for(@policy) do |f| %>
  <% if @policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

      <ul>
      <% @policy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/policies/edit.html.erb
<h1>Editing policy</h1>

<%= render 'form' %>

<%= link_to 'Show', @policy %> |
<%= link_to 'Back', policies_path %>

app/views/policies/index.html.erb
<h1>Listing policies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @policies.each do |policy| %>
  <tr>
    <td><%= policy.name %></td>
    <td><%= link_to 'Show', policy %></td>
    <td><%= link_to 'Edit', edit_policy_path(policy) %></td>
    <td><%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Policy', new_policy_path %>

app/views/policies/index.mobile.erb
<div data-role="header">
  <h1>Policy Information</h1>
  <a href="javascript:history.back()" class = "ui-btn-left" data-role="button">Back</a>
</div>
 
<div data-role="content">
  
PAGE STUCTURE TBC

</div>

app/views/policies/new.html.erb
<h1>New policy</h1>

<%= render 'form' %>

<%= link_to 'Back', policies_path %>

app/views/policies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @policy.name %>
</p>


<%= link_to 'Edit', edit_policy_path(@policy) %> |
<%= link_to 'Back', policies_path %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Google Maps JavaScript API v3 Example: Custom Controls</title>
    <link href="/maps/documentation/javascript/examples/default.css" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>

      var map;
      var hostpitalMarker;
      var dentistMarker;
      var hospitalPos = new google.maps.LatLng(50.897612, -1.391266);
      var dentistPos = new google.maps.LatLng(50.897612, -1.301265);

      /**
       * The HomeControl adds a control to the map that simply
       * returns the user to Chicago. This constructor takes
       * the control DIV as an argument.
       */

      function HomeControl(controlDiv, map) {

        // Set CSS styles for the DIV containing the control
        // Setting padding to 5 px will offset the control
        // from the edge of the map
        controlDiv.style.padding = '5px';

        // Set CSS for the control border
        var controlUI = document.createElement('div');
        controlUI.style.backgroundColor = 'white';
        controlUI.style.borderStyle = 'solid';
        controlUI.style.borderWidth = '2px';
        controlUI.style.cursor = 'pointer';
        controlUI.style.textAlign = 'center';
        controlUI.title = 'Click to only see hospitals';
        controlDiv.appendChild(controlUI);

        // Set CSS for the control interior
        var controlText = document.createElement('div');
        controlText.style.fontFamily = 'Arial,sans-serif';
        controlText.style.fontSize = '12px';
        controlText.style.paddingLeft = '4px';
        controlText.style.paddingRight = '4px';
        controlText.innerHTML = '<b>Hospitals</b>';
        controlUI.appendChild(controlText);

        // Setup the click event listeners: simply set the map to
        // Chicago
        google.maps.event.addDomListener(controlUI, 'click', function() {
          //map.setCenter(chicago)
         	hostpitalMarker.setMap(map);
         	dentistMarker.setMap(null);
        });

      }

      function DentistControl(controlDiv, map) {

        // Set CSS styles for the DIV containing the control
        // Setting padding to 5 px will offset the control
        // from the edge of the map
        controlDiv.style.padding = '5px';

        // Set CSS for the control border
        var controlUI = document.createElement('div');
        controlUI.style.backgroundColor = 'white';
        controlUI.style.borderStyle = 'solid';
        controlUI.style.borderWidth = '2px';
        controlUI.style.cursor = 'pointer';
        controlUI.style.textAlign = 'center';
        controlUI.title = 'Click to only see hospitals';
        controlDiv.appendChild(controlUI);

        // Set CSS for the control interior
        var controlText = document.createElement('div');
        controlText.style.fontFamily = 'Arial,sans-serif';
        controlText.style.fontSize = '12px';
        controlText.style.paddingLeft = '4px';
        controlText.style.paddingRight = '4px';
        controlText.innerHTML = '<b>Dentists</b>';
        controlUI.appendChild(controlText);

        // Setup the click event listeners: simply set the map to
        // Chicago
        google.maps.event.addDomListener(controlUI, 'click', function() {
          //map.setCenter(chicago)
          hostpitalMarker.setMap(null);
          dentistMarker.setMap(map);
        });

      }

      function AllControl(controlDiv, map) {

        // Set CSS styles for the DIV containing the control
        // Setting padding to 5 px will offset the control
        // from the edge of the map
        controlDiv.style.padding = '5px';

        // Set CSS for the control border
        var controlUI = document.createElement('div');
        controlUI.style.backgroundColor = 'white';
        controlUI.style.borderStyle = 'solid';
        controlUI.style.borderWidth = '2px';
        controlUI.style.cursor = 'pointer';
        controlUI.style.textAlign = 'center';
        controlUI.title = 'Click to only see hospitals';
        controlDiv.appendChild(controlUI);

        // Set CSS for the control interior
        var controlText = document.createElement('div');
        controlText.style.fontFamily = 'Arial,sans-serif';
        controlText.style.fontSize = '12px';
        controlText.style.paddingLeft = '4px';
        controlText.style.paddingRight = '4px';
        controlText.innerHTML = '<b>All</b>';
        controlUI.appendChild(controlText);

        // Setup the click event listeners: simply set the map to
        // Chicago
        google.maps.event.addDomListener(controlUI, 'click', function() {
          //map.setCenter(chicago)
          hostpitalMarker.setMap(map);
          dentistMarker.setMap(map);
        });

      }

      function initialize() {
        var mapDiv = document.getElementById('map_canvas');
        var mapOptions = {
          zoom: 11,
          center: hospitalPos,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        map = new google.maps.Map(mapDiv, mapOptions);

        hostpitalMarker = new google.maps.Marker({
		    //position: map.getCenter(),
		    //map: map,
		    position: hospitalPos,
		    title: 'hostpital',
		    animation: google.maps.Animation.DROP

  		});



  		dentistMarker = new google.maps.Marker({
		    position: dentistPos,
		    //map: map,
		    title: 'dentist',
		    animation: google.maps.Animation.DROP
  		});



        //Hospital controls
        var homeControlDiv = document.createElement('div');
        var homeControl = new HomeControl(homeControlDiv, map);

        homeControlDiv.index = 1;
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(homeControlDiv);

        // Dentist controls
        var dentistControlDiv = document.createElement('div');
        var dentistControl = new DentistControl(dentistControlDiv, map);

        dentistControlDiv.index = 2;
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(dentistControlDiv);

        // dispaly all controls
        var allControlDiv = document.createElement('div');
        var allControl = new AllControl(allControlDiv, map);

        allControlDiv.index = 2;
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(allControlDiv);
      }

    </script>
  </head>
  <body onload="initialize()">
    <div id="map_canvas" style="width:500px;height:400px;"></div>
  </body>
</html>

app/views/welcome/index.mobile.erb
<div data-role="content">
    <div class="landingIcons" style="text-align: center;">
        <a href="/policies"><img src="/assets/aviva_logo.png" width="100" height="100"></a><br/>
            My Policy <br/>
            <a href="/welcome/nearestType" > <img src="/assets/google-maps-icon.png" width="100" height="100"></a><br/>
            Where's my nearest?<br/>
          <a href="/faqs"> <img src="/assets/icon_question1.png" width="100" height="100"></a><br/>
             FAQ's
         </div>
</div>

app/views/welcome/landing.html.erb
<h1>Welcome#landing</h1>
<p>Find me in app/views/welcome/landing.html.erb</p>